#!/usr/bin/env bash

Install additional composer dependencies as you would from the command line.
echo "
Installing Composer Dependencies
"
composer require --dev wulfheart/pretty_routes barryvdh/laravel-ide-helper barryvdh/laravel-debugbar
php artisan ide-helper:generate
php artisan ide-helper:models
php artisan ide-helper:meta
# composer require tightenco/mailthief tightenco/quicksand

# To copy standard files to new lambo project place them in ~/.lambo/includes directory.
# echo "
# Copying Include Files
# "
# cp -R ~/.lambo/includes/ $PROJECTPATH

# To add a git commit after given modifications
echo "
Committing after modifications to Git
"
git add .
git commit -am "Initialize Composer dependencies and additional files."
